# Example services.yaml entry

# Service ID
hangup:
  # Service name as shown in UI
  name: Hangup extension
  # Description of the service
  description: Hangup the current call of a extension.
  # If the service accepts entity IDs, target allows the user to specify entities by entity, device, or area. If `target` is specified, `entity_id` should not be defined in the `fields` map. By default it shows only targets matching entities from the same domain as the service, but if further customization is required, target supports the entity, device, and area selectors (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector parameters will automatically be applied to device and area, and device selector parameters will automatically be applied to area. 
  target:
  # Different fields that your service accepts
  fields:
    # Key of the field
    extension:
      # Field name as shown in UI
      name: Extension
      # Description of the field
      description: Extension to hangup.
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: false
      # Example value that can be passed for this field
      example: "101"
      # The default field value
      default: "101"